#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 62
#define LARGE_STATE_COUNT 23
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 3

enum {
  sym_integer = 1,
  sym_float = 2,
  aux_sym_symbol_token1 = 3,
  anon_sym_SLASH = 4,
  sym_keyword = 5,
  anon_sym_DQUOTE = 6,
  aux_sym_string_token1 = 7,
  aux_sym_string_token2 = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_SQUOTE = 15,
  anon_sym_SEMI = 16,
  aux_sym_comment_token1 = 17,
  sym_source_file = 18,
  sym_expression = 19,
  sym_symbol = 20,
  sym_string = 21,
  sym_ratio = 22,
  sym_array = 23,
  sym_map = 24,
  sym_call = 25,
  sym_quote = 26,
  sym_comment = 27,
  aux_sym_source_file_repeat1 = 28,
  aux_sym_string_repeat1 = 29,
  aux_sym_array_repeat1 = 30,
  aux_sym_map_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [aux_sym_symbol_token1] = "symbol_token1",
  [anon_sym_SLASH] = "/",
  [sym_keyword] = "keyword",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_SEMI] = ";",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source_file] = "source_file",
  [sym_expression] = "expression",
  [sym_symbol] = "symbol",
  [sym_string] = "string",
  [sym_ratio] = "ratio",
  [sym_array] = "array",
  [sym_map] = "map",
  [sym_call] = "call",
  [sym_quote] = "quote",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_map_repeat1] = "map_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [aux_sym_symbol_token1] = aux_sym_symbol_token1,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_keyword] = sym_keyword,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym_expression] = sym_expression,
  [sym_symbol] = sym_symbol,
  [sym_string] = sym_string,
  [sym_ratio] = sym_ratio,
  [sym_array] = sym_array,
  [sym_map] = sym_map,
  [sym_call] = sym_call,
  [sym_quote] = sym_quote,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_map_repeat1] = aux_sym_map_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_symbol_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_ratio] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_function = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_function] = "function",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_function, 1},
  [1] =
    {field_arguments, 2},
    {field_function, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 7,
  [10] = 10,
  [11] = 6,
  [12] = 12,
  [13] = 13,
  [14] = 3,
  [15] = 5,
  [16] = 4,
  [17] = 12,
  [18] = 18,
  [19] = 19,
  [20] = 18,
  [21] = 19,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 30,
  [38] = 31,
  [39] = 24,
  [40] = 34,
  [41] = 23,
  [42] = 42,
  [43] = 32,
  [44] = 35,
  [45] = 29,
  [46] = 25,
  [47] = 26,
  [48] = 27,
  [49] = 28,
  [50] = 33,
  [51] = 36,
  [52] = 52,
  [53] = 52,
  [54] = 54,
  [55] = 55,
  [56] = 54,
  [57] = 57,
  [58] = 58,
  [59] = 57,
  [60] = 60,
  [61] = 58,
};

static inline bool aux_sym_symbol_token1_character_set_1(int32_t c) {
  return (c < '<'
    ? (c < '-'
      ? (c < '*'
        ? c == '!'
        : c <= '+')
      : (c <= '-' || (c >= '0' && c <= '9')))
    : (c <= '<' || (c < '_'
      ? (c < 'A'
        ? (c >= '>' && c <= '?')
        : c <= 'Z')
      : (c <= '_' || (c >= 'a' && c <= 'z')))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(13);
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == ',') SKIP(0)
      if (lookahead == '/') ADVANCE(11);
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == ';') ADVANCE(24);
      if (lookahead == '[') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == ']') ADVANCE(18);
      if (lookahead == '{') ADVANCE(19);
      if (lookahead == '}') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (lookahead == '!' ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == ',') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == ',') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == '!' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (lookahead == '!' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (aux_sym_symbol_token1_character_set_1(lookahead)) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_keyword);
      if (lookahead == '!' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == ',') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(14);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == ',') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 25},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 25},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [aux_sym_symbol_token1] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(60),
    [sym_expression] = STATE(10),
    [sym_symbol] = STATE(44),
    [sym_string] = STATE(44),
    [sym_ratio] = STATE(44),
    [sym_array] = STATE(44),
    [sym_map] = STATE(44),
    [sym_call] = STATE(44),
    [sym_quote] = STATE(44),
    [sym_comment] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_integer] = ACTIONS(5),
    [sym_float] = ACTIONS(7),
    [aux_sym_symbol_token1] = ACTIONS(9),
    [anon_sym_SLASH] = ACTIONS(11),
    [sym_keyword] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(23),
  },
  [2] = {
    [sym_expression] = STATE(2),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [aux_sym_array_repeat1] = STATE(2),
    [sym_integer] = ACTIONS(25),
    [sym_float] = ACTIONS(28),
    [aux_sym_symbol_token1] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(34),
    [sym_keyword] = ACTIONS(28),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(40),
    [anon_sym_RBRACK] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(45),
    [anon_sym_LPAREN] = ACTIONS(48),
    [anon_sym_RPAREN] = ACTIONS(43),
    [anon_sym_SQUOTE] = ACTIONS(51),
    [anon_sym_SEMI] = ACTIONS(54),
  },
  [3] = {
    [sym_expression] = STATE(2),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [aux_sym_array_repeat1] = STATE(2),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_RBRACK] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
  [4] = {
    [sym_expression] = STATE(17),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [aux_sym_array_repeat1] = STATE(17),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_RPAREN] = ACTIONS(79),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
  [5] = {
    [sym_expression] = STATE(22),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [aux_sym_map_repeat1] = STATE(13),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
  [6] = {
    [sym_expression] = STATE(14),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [aux_sym_array_repeat1] = STATE(14),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_RBRACK] = ACTIONS(83),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
  [7] = {
    [sym_expression] = STATE(22),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [aux_sym_map_repeat1] = STATE(15),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_RBRACE] = ACTIONS(85),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
  [8] = {
    [sym_expression] = STATE(8),
    [sym_symbol] = STATE(44),
    [sym_string] = STATE(44),
    [sym_ratio] = STATE(44),
    [sym_array] = STATE(44),
    [sym_map] = STATE(44),
    [sym_call] = STATE(44),
    [sym_quote] = STATE(44),
    [sym_comment] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(87),
    [sym_integer] = ACTIONS(89),
    [sym_float] = ACTIONS(92),
    [aux_sym_symbol_token1] = ACTIONS(95),
    [anon_sym_SLASH] = ACTIONS(98),
    [sym_keyword] = ACTIONS(92),
    [anon_sym_DQUOTE] = ACTIONS(101),
    [anon_sym_LBRACK] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(107),
    [anon_sym_LPAREN] = ACTIONS(110),
    [anon_sym_SQUOTE] = ACTIONS(113),
    [anon_sym_SEMI] = ACTIONS(116),
  },
  [9] = {
    [sym_expression] = STATE(22),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [aux_sym_map_repeat1] = STATE(5),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_RBRACE] = ACTIONS(119),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
  [10] = {
    [sym_expression] = STATE(8),
    [sym_symbol] = STATE(44),
    [sym_string] = STATE(44),
    [sym_ratio] = STATE(44),
    [sym_array] = STATE(44),
    [sym_map] = STATE(44),
    [sym_call] = STATE(44),
    [sym_quote] = STATE(44),
    [sym_comment] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(121),
    [sym_integer] = ACTIONS(5),
    [sym_float] = ACTIONS(7),
    [aux_sym_symbol_token1] = ACTIONS(9),
    [anon_sym_SLASH] = ACTIONS(11),
    [sym_keyword] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(23),
  },
  [11] = {
    [sym_expression] = STATE(3),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [aux_sym_array_repeat1] = STATE(3),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_RBRACK] = ACTIONS(123),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
  [12] = {
    [sym_expression] = STATE(2),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [aux_sym_array_repeat1] = STATE(2),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_RPAREN] = ACTIONS(125),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
  [13] = {
    [sym_expression] = STATE(22),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [aux_sym_map_repeat1] = STATE(13),
    [sym_integer] = ACTIONS(127),
    [sym_float] = ACTIONS(130),
    [aux_sym_symbol_token1] = ACTIONS(133),
    [anon_sym_SLASH] = ACTIONS(136),
    [sym_keyword] = ACTIONS(130),
    [anon_sym_DQUOTE] = ACTIONS(139),
    [anon_sym_LBRACK] = ACTIONS(142),
    [anon_sym_LBRACE] = ACTIONS(145),
    [anon_sym_RBRACE] = ACTIONS(148),
    [anon_sym_LPAREN] = ACTIONS(150),
    [anon_sym_SQUOTE] = ACTIONS(153),
    [anon_sym_SEMI] = ACTIONS(156),
  },
  [14] = {
    [sym_expression] = STATE(2),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [aux_sym_array_repeat1] = STATE(2),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_RBRACK] = ACTIONS(159),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
  [15] = {
    [sym_expression] = STATE(22),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [aux_sym_map_repeat1] = STATE(13),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_RBRACE] = ACTIONS(161),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
  [16] = {
    [sym_expression] = STATE(12),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [aux_sym_array_repeat1] = STATE(12),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_RPAREN] = ACTIONS(163),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
  [17] = {
    [sym_expression] = STATE(2),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [aux_sym_array_repeat1] = STATE(2),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_RPAREN] = ACTIONS(165),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
  [18] = {
    [sym_expression] = STATE(16),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
  [19] = {
    [sym_expression] = STATE(48),
    [sym_symbol] = STATE(44),
    [sym_string] = STATE(44),
    [sym_ratio] = STATE(44),
    [sym_array] = STATE(44),
    [sym_map] = STATE(44),
    [sym_call] = STATE(44),
    [sym_quote] = STATE(44),
    [sym_comment] = STATE(44),
    [sym_integer] = ACTIONS(5),
    [sym_float] = ACTIONS(7),
    [aux_sym_symbol_token1] = ACTIONS(9),
    [anon_sym_SLASH] = ACTIONS(11),
    [sym_keyword] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(23),
  },
  [20] = {
    [sym_expression] = STATE(4),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
  [21] = {
    [sym_expression] = STATE(27),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
  [22] = {
    [sym_expression] = STATE(42),
    [sym_symbol] = STATE(35),
    [sym_string] = STATE(35),
    [sym_ratio] = STATE(35),
    [sym_array] = STATE(35),
    [sym_map] = STATE(35),
    [sym_call] = STATE(35),
    [sym_quote] = STATE(35),
    [sym_comment] = STATE(35),
    [sym_integer] = ACTIONS(57),
    [sym_float] = ACTIONS(59),
    [aux_sym_symbol_token1] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [sym_keyword] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(77),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(167), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(169), 12,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [19] = 2,
    ACTIONS(171), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(173), 12,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [38] = 2,
    ACTIONS(175), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(177), 12,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [57] = 2,
    ACTIONS(179), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(181), 12,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [76] = 2,
    ACTIONS(183), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(185), 12,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [95] = 2,
    ACTIONS(187), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(189), 12,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [114] = 2,
    ACTIONS(191), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(193), 12,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [133] = 2,
    ACTIONS(195), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(197), 12,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [152] = 2,
    ACTIONS(199), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(201), 12,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [171] = 2,
    ACTIONS(203), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(205), 12,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [190] = 2,
    ACTIONS(207), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(209), 12,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [209] = 3,
    ACTIONS(215), 1,
      anon_sym_SLASH,
    ACTIONS(211), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(213), 11,
      sym_float,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [230] = 2,
    ACTIONS(211), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(213), 12,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [249] = 2,
    ACTIONS(217), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(219), 12,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [268] = 2,
    ACTIONS(195), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(197), 10,
      ts_builtin_sym_end,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [285] = 2,
    ACTIONS(199), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(201), 10,
      ts_builtin_sym_end,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [302] = 2,
    ACTIONS(171), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(173), 10,
      ts_builtin_sym_end,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [319] = 3,
    ACTIONS(221), 1,
      anon_sym_SLASH,
    ACTIONS(211), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(213), 9,
      ts_builtin_sym_end,
      sym_float,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [338] = 2,
    ACTIONS(167), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(169), 10,
      ts_builtin_sym_end,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [355] = 2,
    ACTIONS(223), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(148), 10,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [372] = 2,
    ACTIONS(203), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(205), 10,
      ts_builtin_sym_end,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [389] = 2,
    ACTIONS(211), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(213), 10,
      ts_builtin_sym_end,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [406] = 2,
    ACTIONS(191), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(193), 10,
      ts_builtin_sym_end,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [423] = 2,
    ACTIONS(175), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(177), 10,
      ts_builtin_sym_end,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [440] = 2,
    ACTIONS(179), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(181), 10,
      ts_builtin_sym_end,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [457] = 2,
    ACTIONS(183), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(185), 10,
      ts_builtin_sym_end,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [474] = 2,
    ACTIONS(187), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(189), 10,
      ts_builtin_sym_end,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [491] = 2,
    ACTIONS(207), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(209), 10,
      ts_builtin_sym_end,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [508] = 2,
    ACTIONS(217), 2,
      sym_integer,
      aux_sym_symbol_token1,
    ACTIONS(219), 10,
      ts_builtin_sym_end,
      sym_float,
      anon_sym_SLASH,
      sym_keyword,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_SEMI,
  [525] = 4,
    ACTIONS(225), 1,
      anon_sym_DQUOTE,
    ACTIONS(227), 1,
      aux_sym_string_token1,
    ACTIONS(229), 1,
      aux_sym_string_token2,
    STATE(55), 1,
      aux_sym_string_repeat1,
  [538] = 4,
    ACTIONS(227), 1,
      aux_sym_string_token1,
    ACTIONS(229), 1,
      aux_sym_string_token2,
    ACTIONS(231), 1,
      anon_sym_DQUOTE,
    STATE(55), 1,
      aux_sym_string_repeat1,
  [551] = 4,
    ACTIONS(233), 1,
      anon_sym_DQUOTE,
    ACTIONS(235), 1,
      aux_sym_string_token1,
    ACTIONS(237), 1,
      aux_sym_string_token2,
    STATE(52), 1,
      aux_sym_string_repeat1,
  [564] = 4,
    ACTIONS(239), 1,
      anon_sym_DQUOTE,
    ACTIONS(241), 1,
      aux_sym_string_token1,
    ACTIONS(244), 1,
      aux_sym_string_token2,
    STATE(55), 1,
      aux_sym_string_repeat1,
  [577] = 4,
    ACTIONS(247), 1,
      anon_sym_DQUOTE,
    ACTIONS(249), 1,
      aux_sym_string_token1,
    ACTIONS(251), 1,
      aux_sym_string_token2,
    STATE(53), 1,
      aux_sym_string_repeat1,
  [590] = 1,
    ACTIONS(253), 1,
      sym_integer,
  [594] = 1,
    ACTIONS(255), 1,
      aux_sym_comment_token1,
  [598] = 1,
    ACTIONS(257), 1,
      sym_integer,
  [602] = 1,
    ACTIONS(259), 1,
      ts_builtin_sym_end,
  [606] = 1,
    ACTIONS(261), 1,
      aux_sym_comment_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(23)] = 0,
  [SMALL_STATE(24)] = 19,
  [SMALL_STATE(25)] = 38,
  [SMALL_STATE(26)] = 57,
  [SMALL_STATE(27)] = 76,
  [SMALL_STATE(28)] = 95,
  [SMALL_STATE(29)] = 114,
  [SMALL_STATE(30)] = 133,
  [SMALL_STATE(31)] = 152,
  [SMALL_STATE(32)] = 171,
  [SMALL_STATE(33)] = 190,
  [SMALL_STATE(34)] = 209,
  [SMALL_STATE(35)] = 230,
  [SMALL_STATE(36)] = 249,
  [SMALL_STATE(37)] = 268,
  [SMALL_STATE(38)] = 285,
  [SMALL_STATE(39)] = 302,
  [SMALL_STATE(40)] = 319,
  [SMALL_STATE(41)] = 338,
  [SMALL_STATE(42)] = 355,
  [SMALL_STATE(43)] = 372,
  [SMALL_STATE(44)] = 389,
  [SMALL_STATE(45)] = 406,
  [SMALL_STATE(46)] = 423,
  [SMALL_STATE(47)] = 440,
  [SMALL_STATE(48)] = 457,
  [SMALL_STATE(49)] = 474,
  [SMALL_STATE(50)] = 491,
  [SMALL_STATE(51)] = 508,
  [SMALL_STATE(52)] = 525,
  [SMALL_STATE(53)] = 538,
  [SMALL_STATE(54)] = 551,
  [SMALL_STATE(55)] = 564,
  [SMALL_STATE(56)] = 577,
  [SMALL_STATE(57)] = 590,
  [SMALL_STATE(58)] = 594,
  [SMALL_STATE(59)] = 598,
  [SMALL_STATE(60)] = 602,
  [SMALL_STATE(61)] = 606,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(34),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(35),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(36),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(36),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(56),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(11),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(9),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(20),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(21),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(58),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(40),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(44),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(51),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(51),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(54),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(6),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(7),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(18),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(19),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(61),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2), SHIFT_REPEAT(34),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2), SHIFT_REPEAT(35),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2), SHIFT_REPEAT(36),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2), SHIFT_REPEAT(36),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2), SHIFT_REPEAT(56),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2), SHIFT_REPEAT(11),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2), SHIFT_REPEAT(9),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2), SHIFT_REPEAT(20),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2), SHIFT_REPEAT(21),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2), SHIFT_REPEAT(58),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, .production_id = 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, .production_id = 2),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ratio, 3),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ratio, 3),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 2),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 2),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 2),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 2),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, .production_id = 1),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, .production_id = 1),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 1),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(55),
  [244] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(55),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [259] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_yeti(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
